.gitignore
log-generator/log-generator.js
log-generator/package-lock.json
log-generator/package.json

This is a simple script that endlessly logs to the console. It's using
either the pino or the winston log enrichers and the newrelic
instrumentation, for testing purposes.
Closes https://github.com/newrelic/node-newrelic/issues/1143

log-generator: new sample script to generate lots of logs

---

log-generator/.eslintrc.js
log-generator/log-generator.js

This should be a little more realistic instead of logging everything at the info log levels.
Also adds some basic linting.

Log generator: randomly spread logs between log levels

---

README.md

grammatical corrections

---

log-generator/README.md

NEWRELIC-3535 update README for node examples

NEWRELIC-3535 update README for node examples

---

code-level-metrics/.gitignore
code-level-metrics/Dockerfile
code-level-metrics/README.md
code-level-metrics/docker-compose.yml
code-level-metrics/entrypoint.sh
code-level-metrics/express/.dockerignore
code-level-metrics/express/index.js
code-level-metrics/express/make-requests.sh
code-level-metrics/express/package-lock.json
code-level-metrics/express/package.json
code-level-metrics/sample.env

* Added a sample application written in express to fully test CodeStream integration
Closes NEWRELIC-5570
We will add to this application to add sample custom instrumentation via startSegment, startBackgroundTransaction and startWebTransaction.  
**Note**: You must have [Docker](https://docs.docker.com/get-docker/) and [Docker Compose](https://docs.docker.com/compose/install/) installed.  The steps below are using [hey](https://github.com/rakyll/hey) to generate load on the sample app.
1. Clone or fork this repository.
1. Copy `sample.env` to `.env` and fill out the following keys:
```sh
NEW_RELIC_LICENSE_KEY=<New Relic License Key>
```
1. Start containers `docker-compose up -d --build`
1. Navigate to your application in New Relic One and explore the attributes on the spans for middleware …

NEWRELIC-5570 added sample app with injector of traffic

---

code-level-metrics/entrypoint.sh
code-level-metrics/express/.eslintrc.js
code-level-metrics/express/index.js
code-level-metrics/express/instrumentation.js
code-level-metrics/express/job-thing.js
code-level-metrics/express/make-requests.sh
code-level-metrics/express/package-lock.json
code-level-metrics/express/package.json
code-level-metrics/express/util.js

* Added instrumentation to code-level-metrics example that exercises `startWebTransaction`, `startBackgroundTransaction` and `startSegment`.

NEWRELIC-5570: add instrumentation to the code-level metrics example

---

logs-in-context/fluentd/Dockerfile

* Updated fluentd image to 1.15-1 for vulnerability fixes
Keeping our repo clean and up to date on deps, in this case, the fluentd docker image for the logs in context demo

Updated fluentd image to 1.15-1 for vulnerability fixes

---

prisma-app/sample.env

Oops, forgot to add this before in https://github.com/newrelic/newrelic-node-examples/pull/44

prisma-app: add sample.env

---

CONTRIBUTING.md

Updated Slack link, per JIRA ticket https://issues.newrelic.com/browse/NR-72269

Updated Slack link

---

CONTRIBUTING.md
README.md

* Update README header image to latest OSS office required images
Closes NEWRELIC-7076
Closes https://github.com/newrelic/newrelic-node-examples/issues/53
* New header image supports both light and dark mode, and repolinter complains about using the dark only image

chore: update to newest examples header

---

error-fingerprinting/.eslintrc.js
error-fingerprinting/README.md
error-fingerprinting/helpers.js
error-fingerprinting/index.js
error-fingerprinting/newrelic.js
error-fingerprinting/package-lock.json
error-fingerprinting/package.json

* Added example app to demonstrate usage of `newrelic.setErrorGroupCallback`
Part of https://github.com/newrelic/node-newrelic/pull/1555

chore: add new Error Fingerprinting example app

---

mock-infinite-tracing-server/index.js
mock-infinite-tracing-server/inifinite-trace.proto
mock-infinite-tracing-server/package-lock.json
mock-infinite-tracing-server/package.json

added simple inifinite trace mock server

---

nestjs/app/README.md

* Added more description in the Nest.js application README file.
* NEWRELIC-8082

fix(nestjs): Add a better explanation to the base README.

---

elasticsearch/README.md
elasticsearch/app/server.js
elasticsearch/newrelic.js
elasticsearch/package-lock.json
elasticsearch/package.json

* Added skeleton for elasticsearch app
This is a skeleton for @mchavez-newrelic to start with documenting how to instrument elasticsearch with `instrumentDatastore`

chore: add elasticsearch app skeleton for ignite rotation

---

esm-app/README.md

I removed config in #121 but forgot to update the verbiage in the README

chore: updated readme to remove info around custom instrumentation via config

---

openai/README.md
openai/index.js
openai/package-lock.json
openai/package.json

feat: remove setLlmMetadata as the api has been removed. Update conversation_id to llm.conversation_id

---

aws-bedrock-app/README.md

docs: fixed typo in sample json for feedback

---

aws-bedrock-app/package-lock.json

Updating package lock to get the new version of `@newrelic/aws-sdk` which has a feature complete version of aws sdk.

chore: updated lock to include latest aws-sdk instrumentation

---

aws-bedrock-app/package-lock.json
aws-bedrock-app/package.json

Updates agent to get the latest changes for ai monitoring

chore: updates to latest agent version to get the llm attributes on transaction

---

simple-express-app/package-lock.json
simple-express-app/package.json

chore: update agent on simple express app

---

aws-bedrock-app/package-lock.json
aws-bedrock-app/package.json
openai/index.js
openai/package-lock.json
openai/package.json

Updates openai and bedrock sample apps to the latest version of agent that has AIM features GA.

chore: updated agent version to the GA version that includes all AIM features

---

langchain/README.md
langchain/custom-tool.js
langchain/docker-compose.yml
langchain/index.js
langchain/newrelic.js
langchain/package-lock.json
langchain/package.json

Updated LangChain example to show vector search and tools calls.
Closes #171 
Closes NR-218735

feat: Updated LangChain example

---

nextjs-legacy/README.md
nextjs-legacy/package.json

Removed steps to pre-register browser agent entity.  This is not needed. Our agent will return the browser agent correctly. Also load `dotenv/config` in build so it can load agent for the static pages.

docs: cleanup of next js pages router example readme

---

prisma-app/README.md
prisma-app/app/package-lock.json
prisma-app/app/package.json
prisma-app/entrypoint.sh

Closes #110
I am not sure what is going on but I updated README to manually invoke the `make-requests.sh` within docker container from host and this works.  If you follow the steps in readme you will get a working example app now. I also updated the agent to the latest.

chore: fixed prisma example app to run the script from machine

---

prisma-app/README.md

chore: added step to stop containers for prisma app

---

custom-instrumentation/instrument-messages/README.md
custom-instrumentation/instrument-messages/instrumentation.js
custom-instrumentation/instrument-messages/package.json
custom-instrumentation/instrument-webframework/README.md
custom-instrumentation/instrument-webframework/instrumentation.js
custom-instrumentation/instrument-webframework/package.json

This PR updates the custom-instrumentation examples by constructing specs and fixing some README language

chore: fixed custom instrumentation examples by defining specs

---

custom-instrumentation/README.md
custom-instrumentation/instrument-datastore/README.md
custom-instrumentation/instrument-datastore/index.js
custom-instrumentation/instrument-datastore/instrumentation.js
custom-instrumentation/instrument-datastore/simple-datastore.js
custom-instrumentation/instrument-messages/README.md
custom-instrumentation/instrument-messages/index.js
custom-instrumentation/instrument-messages/instrumentation.js
custom-instrumentation/instrument-messages/nifty-messages.js
custom-instrumentation/instrument-webframework/README.md
custom-instrumentation/instrument-webframework/index.js
custom-instrumentation/instrument-webframework/instrumentation.js
custom-instrumentation/instrument-webframework/simple-framework.js
custom-instrumentation/instrument/README.md
custom-instrumentation/instrument/index.js
custom-instrumentation/instrument/instrumentation.js
custom-instrumentation/instrument/job-queue.js

Copied over the relevant comments from `node-newrelic/examples/shim` into the `custom-instrumentation` folder.

chore: Annotate from tutorials

---

nextjs/nextjs-legacy/README.md

- Add line about install packages in nextjs legacy example
https://github.com/newrelic/newrelic-node-examples/pull/295#discussion_r1750148247
As discussion link above, add install packages between step2 and step3

add readme about install pacakges in nextjs legacy example

---

knex/package.json

chore: updated express/body-parser to do caret matching to avoid dependabot getting on my case

---

opentelemetry-example/README.md
opentelemetry-example/server/controllers/fetch_controller.js
opentelemetry-example/server/controllers/http_controller.js

I addd qp's to the outbound calls to verify they are getting set on segments/spans. I also added more example URLs to test in readme.

chore: added query params to http/fetch calls, added more to readme

---

mock-infinite-tracing-server/README.md

chore: tweaked readme to include a new config for adding attribute to force ingest service to always accept span

---

README.md
opentelemetry-graphql/README.md
opentelemetry-graphql/client-federation.js
opentelemetry-graphql/client.js
opentelemetry-graphql/countries-service.js
opentelemetry-graphql/docker/collector-config.yaml
opentelemetry-graphql/docker/docker-compose.yaml
opentelemetry-graphql/docker/prometheus.yaml
opentelemetry-graphql/env-client.sample
opentelemetry-graphql/env-server.sample
opentelemetry-graphql/env.sample
opentelemetry-graphql/newrelic.js
opentelemetry-graphql/otel-instrumentation.js
opentelemetry-graphql/package.json
opentelemetry-graphql/schema.js
opentelemetry-graphql/server-apollo.js
opentelemetry-graphql/server-express.js
opentelemetry-graphql/server-federation.js

feat: GraphQL OTel bridge example app

---

azure-functions/.dockerignore
azure-functions/.funcignore
azure-functions/.gitignore
azure-functions/.npmrc
azure-functions/Dockerfile
azure-functions/README.md
azure-functions/example_local.settings.json
azure-functions/host.json
azure-functions/package.json
azure-functions/src/functions/HttpExample.js
azure-functions/src/functions/HttpGeneric.js
azure-functions/src/functions/HttpGetWithHandler.js
azure-functions/src/functions/HttpGetWithOptions.js
azure-functions/src/functions/HttpPost.js
azure-functions/src/functions/TimerExample.js

As we're working on Azure Functions instrumentation, this is an example for local testing and development. This should remain in draft until Azure-Function-specific instrumentation is released in the Node agent. 
Closes NR-381815
Closes https://github.com/newrelic/node-newrelic/issues/3005

feat: Added Azure Functions example for local testing and development

---

gcp-pubsub/package.json

This PR upgrades `@google-cloud/pubsub` to version 5.1.0 which had the last set of fixes we made to the library.

chore: updated gcp-pubsub to 5.1.0
